<?php
namespace App\Model\Table;
use Cake\ORM\Table;

class PostsTable extends Table
{
    public function initialize(array $config) {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->addBehavior('Timestamp');  

        $this->belongsTo('Users', [
            'className' => 'Users',
            'foreignKey' => 'user_id'
        ]);   

        $this->hasMany('Likes', [
            'className' => 'Likes',
            'foreignKey' => 'post_id'
        ]);   

        $this->hasMany('Comments', [
            'className' => 'Comments',
            'foreignKey' => 'post_id'
        ]);    

    }

    
}
