<?php
namespace App\Model\Table;
use Cake\ORM\Table;

class UsersTable extends Table
{
    public function initialize(array $config) {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->addBehavior('Timestamp');      

        $this->hasMany('Posts', [
            'className' => 'Posts',
            'foreignKey' => 'user_id'
        ]);  

        $this->hasMany('Comments', [
            'className' => 'Comments',
            'foreignKey' => 'commenter_id'
        ]);  
    }

    
}
